# Generated by Django 5.0.2 on 2024-02-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
